[package]
name = "ace"
version = "0.2.0"
authors = ["wyhaya <wyhaya@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Parsing command line arguments"
readme = "README.md"

keywords = [
    "command",
    "parsing",
    "arguments"
]

[dependencies]